//
function script4206(int0: component, int1: struct): void {
    if (((int0 == comp(-1, 65535)) || (int1 == -1 as struct))) {
        return;
    };
    var int2 = struct_getparam(int1, 3798);
    var int3 = struct_getparam(int1, 3800);
    var int4 = struct_getparam(int1, 3804);
    var int5 = struct_getparam(int1, 3806);
    var int6 = struct_getparam(int1, 3803);
    var int7 = struct_getparam(int1, 1354);
    var int8 = struct_getparam(int1, 3802);
    var int9 = struct_getparam(int1, 1357);
    var int10 = struct_getparam(int1, 1358);
    CC_DELETEALL(int0);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 1, 0);
    CC_SETSIZE(14, 16384, 1, 2);
    CC_SETGRAPHIC(int8);
    CC_SETTILING(true);
    CC_SETTRANS(int10);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 1, 2);
    CC_SETSIZE(14, 10000, 1, 2);
    CC_SETGRAPHIC(int9);
    CC_SETTILING(true);
    CC_SETTRANS(int10);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 0, 0);
    CC_SETSIZE(7, 16384, 0, 2);
    CC_SETGRAPHIC(int6);
    CC_SETTRANS(int10);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 2, 0);
    CC_SETSIZE(7, 16384, 0, 2);
    CC_SETGRAPHIC(int6);
    CC_SETHFLIP(true);
    CC_SETTRANS(int10);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 0, 0);
    CC_SETSIZE(7, 7, 0, 0);
    CC_SETGRAPHIC(int3);
    CC_SETTRANS(int10);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 1, 0);
    CC_SETSIZE(14, 7, 1, 0);
    CC_SETGRAPHIC(int2);
    CC_SETTILING(true);
    CC_SETTRANS(int10);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 2, 0);
    CC_SETSIZE(7, 7, 0, 0);
    CC_SETGRAPHIC(int3);
    CC_SETTRANS(int10);
    CC_SETHFLIP(true);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 0, 2);
    CC_SETSIZE(7, 10000, 0, 2);
    CC_SETGRAPHIC(int7);
    CC_SETTILING(true);
    CC_SETTRANS(int10);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 2, 2);
    CC_SETSIZE(7, 10000, 0, 2);
    CC_SETGRAPHIC(int7);
    CC_SETTILING(true);
    CC_SETHFLIP(true);
    CC_SETTRANS(int10);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 0, 2);
    CC_SETSIZE(7, 7, 0, 0);
    CC_SETGRAPHIC(int5);
    CC_SETTRANS(int10);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 1, 2);
    CC_SETSIZE(14, 7, 1, 0);
    CC_SETGRAPHIC(int4);
    CC_SETTILING(true);
    CC_SETTRANS(int10);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETPOSITION(0, 0, 2, 2);
    CC_SETSIZE(7, 7, 0, 0);
    CC_SETGRAPHIC(int5);
    CC_SETTRANS(int10);
    CC_SETHFLIP(true);
    return;
}