//
function script16742(int0: int): void {
    var int1 = script2948();
    var int2 = comp(744, 134);
    var int3 = comp(744, 335);
    switch (int1) {
        case 49: {
            if ((varclient_1100 != 49)) {
                script9804();
                script2954(0);
                script2950(int1, 1, "The Jagex Account Guardian is protecting this account.<br><br>This device is not recognised. An email has been sent to the validated email address.<br><br>Follow the link in the email to add this device. (Please check your spam folders)", 13105, "Resend Email");
            };
            varclient_1100 = 49;
            return;
        }
        case 52: {
            if ((varclient_1100 != 52)) {
                script9804();
                script2954(0);
                script2950(int1, 1, "The Jagex Account Guardian is protecting this account.<br><br>You need to validate this device to use with your account. Please follow the instructions in the window that will open shortly.<br><br>If no window appears, we can send you an email to complete the process.", 13105, "Send Email");
            };
            varclient_1100 = 52;
            return;
        }
        case 56: {
            if ((varclient_1100 != 56)) {
                script9804();
                script2954(0);
                script9803("Enter the 6-digit code generated by your Authenticator app.");
            };
            varclient_1100 = 56;
            return;
        }
        case 57: {
            if ((varclient_1100 != 57)) {
                script9804();
                script2954(0);
                script9803("The code you entered was incorrect.<br>Please try again.");
            };
            varclient_1100 = 57;
            return;
        }
        case 42: {
            varclient_1100 = 42;
            return;
        }
        case 43: {
            varclient_1100 = 43;
            return;
        }
        case -3: {
            IF_SETONCLICK(callback(), int2);
            script15662("Signing in...", -1, 0);
            varclient_1100 = -3;
            return;
        }
        case 63: {
            IF_SETONCLICK(callback(), int2);
            script15662("Signing in...", -1, 0);
            varclient_1100 = 63;
            return;
        }
        case 1409: {
            varclient_1100 = 1409;
            script4142(-1);
            return;
        }
    };
    if ((varclient_1100 == -3)) {
        script2954(0);
    };
    var int4 = 0;
    var string0 = "";
    if ((int1 == 21)) {
        varclient_1100 = 21;
        IF_SETONCLICK(callback(), int2);
        if ((varclient_200 == 0)) {
            varclient_200 = LOGIN_HOPTIME();
        };
        varclient_200 = (varclient_200 - 1);
        if ((varclient_200 <= 0)) {
            IF_SETONTIMER(callback(), int2);
            if ((int0 == 0)) {
                script2945();
            } else if ((int0 == 8)) {
                script15262();
            } else {
                script4634(int0);
            };
            return;
        };
        int4 = (varclient_200 / 50);
        if ((int4 == 1)) {
            string0 = "You have only just left another world. Your profile will be transferred in<br>1 second.";
        } else {
            string0 = `You have only just left another world. Your profile will be transferred in<br>${inttostring(int4, 10)} seconds.`;
        };
        if ((IF_GETHIDE(int3) == true)) {
            script2950(int1, 0, string0, 2611, "Abort Login");
        } else {
            script3233(string0);
        };
        return;
    };
    script2954(0);
    var int5 = 0;
    var string1 = "";
    if ((int1 == 1)) {
        IF_SETONCLICK(callback(), int2);
        int5 = ((500 - varclient_201) / 50);
        if ((varclient_202 == 0)) {
            if ((int5 == 1)) {
                string1 = "Could not display video advertisement. Login will continue in 1 second.";
            } else {
                string1 = `Could not display video advertisement. Login will continue in ${inttostring(int5, 10)} seconds`;
            };
        } else if ((varclient_201 < 500)) {
            if ((int5 == 1)) {
                string1 = "Displaying video advertisement. Login will continue in 1 second.";
            } else {
                string1 = `Displaying video advertisement. Login will continue in ${inttostring(int5, 10)} seconds.`;
            };
        } else {
            string1 = "Displaying video advertisement. Login will continue in 0 seconds.";
        };
        script2950(int1, 0, string1, 2611, "");
        varclient_201 = (varclient_201 + 1);
        script2954(0);
        LOGIN_CONTINUE();
        return;
    };
    script2954(0);
    IF_SETONCLICK(callback(script2944), int2);
    IF_SETONTIMER(callback(), 48759119);
    var string2 = "";
    var int6 = 1;
    var int7 = 0;
    var int8 = 2608;
    var string3 = "";
    var int9 = 0;
    var int10 = 0;
    var int11 = 1;
    var string4 = "Back";
    var int12 = 0;
    var int13 = 0;
    var int14 = 0;
    var int15 = 0;
    switch (int1) {
        case -2: {
            script2954(0);
            script2940(8);
            return;
        }
        case 29: {
            switch (LOGIN_DISALLOWRESULT()) {
                case 0: {
                    string2 = "You must have a Combat Level of at least 20 (not including Summoning) to enter a Bounty Hunter world.";
                    break;
                }
                case 1: {
                    string2 = "You are currently carrying lent items and cannot enter a PvP world.";
                    break;
                }
                case 2: {
                    string2 = "You must be standing in the Wilderness or Edgeville to enter this bounty world.";
                    break;
                }
                case 3: {
                    string2 = "You must have a total skill level of 1,000 or greater to enter this world.";
                    break;
                }
                case 5: {
                    string2 = "You must have a total skill level of 1,500 or greater to enter this world.";
                    break;
                }
                case 6: {
                    string2 = "You must have a total skill level of 2,000 or greater to enter this world.";
                    break;
                }
                case 7: {
                    string2 = "You must have a total skill level of 2,600 or greater to enter this world.";
                    break;
                }
                case 4: {
                    string2 = "You must move to a safe area before you can log in to a Bounty Hunter world.";
                    break;
                }
                case 9: {
                    string2 = "This server is for staff only.";
                    break;
                }
                case 10: {
                    string2 = "You cannot enter a Classic Mode world while in the tutorial.";
                    break;
                }
                case 12: {
                    string2 = "Your account has been involved in serious rule breaking, and so has been temporarily disabled.";
                    break;
                }
                case 13: {
                    string2 = "You are standing in a members-only area. To play on this world, move to a free area first.";
                    break;
                }
                case 15: {
                    string2 = "You can not login to a Classic Mode world on mobile.";
                    break;
                }
                case 17: {
                    string2 = "Your account cannot currently log into this world. Please try another world.";
                    break;
                }
                default: {
                    string2 = "Unexpected server response. Please try using a different world.";
                    break;
                }
            };
            break;
        }
        case 46: {
            string2 = "This instance is marked for deletion/rebuild. Please try using a different world.";
            break;
        }
        case 45: {
            switch (LOGIN_DISALLOWTRIGGER()) {
                case 0: {
                    switch (LOGIN_DISALLOWRESULT()) {
                        case 0: {
                            string2 = "You must be near the TzHaar Fight Pit entrance to enter a global match.";
                            break;
                        }
                        default: {
                            string2 = "Unable to log in. Please try using a different world.";
                            break;
                        }
                    };
                    break;
                }
                case 1: {
                    switch (LOGIN_DISALLOWRESULT()) {
                        case 1: {
                            string2 = "There was an error connecting to your meeting room. Please try again.";
                            break;
                        }
                        case 2: {
                            string2 = "You need a higher rank to enter that private tent.";
                            break;
                        }
                        case 3: {
                            string2 = "You need an invitation to enter that private room.";
                            break;
                        }
                        default: {
                            string2 = "Unable to log in. Please try using a different world.";
                            break;
                        }
                    };
                    break;
                }
                case 5: {
                    switch (LOGIN_DISALLOWRESULT()) {
                        case 0: {
                            string2 = "The instance you attempted to join is full.";
                            break;
                        }
                        case 1: {
                            string2 = "You can't join that instance as you or your follower are carrying items.";
                            break;
                        }
                        default: {
                            string2 = "Unable to log in. Please try using a different world.";
                            break;
                        }
                    };
                    break;
                }
                default: {
                    string2 = "Unexpected server response. Please try using a different world.";
                    break;
                }
            };
            break;
        }
        case -5: {
            string2 = "Connection timed out. Please try using a different world.";
            break;
        }
        case -4: {
            string2 = "Error connecting to server.";
            break;
        }
        case -1: {
            string2 = "No response from server. Please try using a different world.";
            break;
        }
        case 5: {
            string2 = "Your account has not logged out from its last session or the server is too busy to handle your request. Please try again in a few minutes or try a different server.";
            string3 = "OK";
            break;
        }
        case 7: {
            string2 = "This world is full. Please use a different world.";
            break;
        }
        case 8: {
            string2 = "Unable to connect: login server offline.";
            break;
        }
        case 9: {
            string2 = "Login limit exceeded: too many connections from your address.";
            break;
        }
        case 10: {
            string2 = "Unable to connect: bad session id.";
            break;
        }
        case 13: {
            string2 = "Could not complete login. Please try using a different world.";
            break;
        }
        case 16: {
            string2 = "Too many login attempts.<br>You can use the Jagex Launcher to continue playing.<br>Download from <col=134ED8>https://www.jagex.com/launcher</col>";
            break;
        }
        case 17: {
            string2 = "You are standing in a members-only area. To play on this world, move to a free area first.";
            break;
        }
        case 20: {
            string2 = "Invalid loginserver requested. Please try using a different world.";
            break;
        }
        case 22: {
            string2 = "Sorry, we had trouble logging you in. Please try again.";
            break;
        }
        case 23: {
            string2 = "No reply from login server. Please wait a minute and try again.";
            break;
        }
        case 24: {
            string2 = "Error loading your profile. Please contact customer support.";
            break;
        }
        case 25: {
            string2 = "Unexpected loginserver response. Please try using a different world.";
            break;
        }
        case 26: {
            string2 = "This computer's address has been blocked, as it was used to break our rules.";
            break;
        }
        case 27: {
            string2 = "Service unavailable.";
            break;
        }
        case 36: {
            string2 = "Unable to connect: authentication server offline.";
            break;
        }
        case 37:
        case 62: {
            string2 = "Your account is currently inaccessible. Please try again in a few minutes.";
            break;
        }
        case 39: {
            string2 = "The instance you tried to join no longer exists. Please try using a different world.";
            break;
        }
        case 41: {
            string2 = "The instance you tried to join is full. Please try back later or try using a different world.";
            break;
        }
        case 44: {
            string2 = "Our systems are currently unavailable. Please try again in a few minutes.";
            break;
        }
        case 55: {
            string2 = "Sorry, but your account is not eligible to play.<br>For more information, please take a look at our privacy policy.";
            string3 = "Privacy Policy";
            break;
        }
        case 35: {
            string2 = "Your session has expired. Please click 'Back' in your browser to renew it.";
            break;
        }
        case 14: {
            int6 = 0;
            int8 = 2610;
            if ((script13749() == true)) {
                string2 = "RuneScape is currently updating. Please wait a few minutes and restart the app to retry.";
            } else {
                string2 = "RuneScape is currently updating. Please wait a few minutes and restart the game to retry.";
            };
            break;
        }
        case 6: {
            int6 = 0;
            int8 = 2610;
            if ((script13749() == true)) {
                string2 = "RuneScape has been updated! Please restart the app to retry.";
            } else {
                string2 = "RuneScape has been updated! Please restart the game to retry.";
            };
            break;
        }
        case 3: {
            if ((varclient_1414 == 1)) {
                string2 = "Invalid username or password.";
            } else if ((varclient_1414 == 2)) {
                string2 = "Invalid email or password.";
            } else {
                string2 = "Invalid login or password.";
            };
            string2 = strconcat(string2, "<br><br>For accounts created after the 24th of November 2010, please use your email address to login. Otherwise please login with your username.<br><br>You may need to use the Jagex Launcher to continue playing. Download from <col=134ED8>https://www.jagex.com/launcher</col>");
            string3 = "Forgotten your password?";
            script380(3989 as dbrow);
            break;
        }
        case 4: {
            string2 = "Your account has been involved in serious rule breaking.";
            string3 = "More info";
            break;
        }
        case 11: {
            string2 = "Your password is an extremely common choice, and is not secure. You must change it before you can login.";
            string3 = "Change Password";
            break;
        }
        case 18: {
            int8 = 2612;
            string2 = "Your account has been locked due to suspicious activity. Please recover your account.";
            string3 = "Recover Account";
            break;
        }
        case 30: {
            string2 = "This is not a member's account; please choose a 'free' world from the website to play on this account.";
            if ((script6431() == false)) {
                string3 = "Subscribe";
            };
            break;
        }
        case 31: {
            string2 = "You must change your account's display name before you can login.";
            string3 = "Change Display Name";
            break;
        }
        case 19: {
            string2 = "Fullscreen is currently a members-only feature. To log in, exit fullscreen via the options menu or use a member's account.";
            if ((script6431() == false)) {
                string3 = "Subscribe";
            };
            break;
        }
        case 12: {
            string2 = "You need a member's account to log in to this world. Please subscribe or use a different world.";
            if ((script6431() == false)) {
                string3 = "Subscribe";
            };
            break;
        }
        case 40: {
            string2 = "You need a member's account to log in to this world. Please subscribe or use a different world.";
            if ((script6431() == false)) {
                string3 = "Subscribe";
            };
            break;
        }
        case 32: {
            string2 = "The unpaid balance on your account needs to be settled before you can log into game.";
            if ((script6431() == false)) {
                string3 = "Unpaid balance";
            };
            break;
        }
        case 47:
        case 51: {
            string2 = "You need to validate your email address to log in.";
            break;
        }
        case 48: {
            if ((script13749() == true)) {
                string2 = "Your game session has now ended.<br><br>To play again, please close the app and wait 5 minutes before reloading it. ";
            } else {
                string2 = "Your game session has now ended.<br><br>To play again, please close your game client and wait 5 minutes before reloading the game. ";
            };
            break;
        }
        case 53: {
            LOGIN_BAN_DURATION();
            varclient_200 = stack();
            [int13, int14, int15] = script6716(varclient_200);
            string2 = `Your ban will be lifted in<br>${inttostring(int13, 10)} hours, ${inttostring(int14, 10)} minutes, ${inttostring(int15, 10)} seconds`;
            IF_SETONTIMER(callback(script6715), 48759119);
            string3 = "More info";
            break;
        }
        case 50: {
            string2 = "The Jagex Account Guardian is protecting this account.<br><br>This device is not recognised.<br><br>No new devices can be added for up to 24 hours as too many failed attempts to answer the security questions have been made.<br><br>During this time access will still be granted to any devices already trusted.";
            int8 = 13105;
            break;
        }
        case 38: {
            string2 = "Your account does not currently have access to this Beta.";
            break;
        }
        case 58: {
            string2 = "Jagex Account Guardian cannot be used with the NXT Beta Client. Please disable JAG via Account Settings before continuing.<br><br>We strongly suggest activating the RuneScape Authenticator to enhance the security of your account.";
            string3 = "Open Account Settings";
            break;
        }
        case 59: {
            string2 = "Jagex Account Guardian cannot be used with the NXT Beta Client. Please disable JAG via Account Settings before continuing.";
            string3 = "Open Account Settings";
            break;
        }
        case 60: {
            string2 = "Connection timed out. Please try again.";
            break;
        }
        case 61: {
            string2 = "You need to set your date of birth to continue. Please log into the website to do so.";
            break;
        }
        case 64: {
            string2 = "Single Sign on timed out. Please try again in a few moments.";
            break;
        }
        case 65: {
            string2 = "Single Sign on failed. Please try again in a few moments.";
            break;
        }
        case 1401: {
            string2 = "Single Sign on failed because your token has expired. Please try re-entering your login details.";
            break;
        }
        case 1402: {
            string2 = "Single Sign on failed because you exited without signing in.";
            break;
        }
        case 1403: {
            if ((CLIENTTYPE() == 8)) {
                string2 = "Sign on was interrupted or cancelled. Please check your internet connection or try again later.";
            } else {
                string2 = "Could not connect. Please check your internet connection or try again later.";
            };
            break;
        }
        case 1404: {
            string2 = "Single Sign on failed because your access is unauthorized. Please try re-entering your login details.";
            break;
        }
        case 1405: {
            string2 = "Revoking token action unsuccessful.";
            break;
        }
        case 1406: {
            string2 = "Single Sign on failed because your account creation was unsuccessful. Please ensure you have entered a valid date of birth.";
            break;
        }
        case 1407: {
            string2 = "Single Sign on failed because you have a pending transaction.";
            break;
        }
        case 1408: {
            string2 = "Single Sign on failed as the browser was unable to open. Please check your internet connection or try again later.";
            break;
        }
        case 1410: {
            string2 = "Linking accounts failed as the browser was unable to open. Please check your internet connection or try again later.";
            break;
        }
        default: {
            string2 = "Unexpected server response. Please try using a different world.";
            break;
        }
    };
    script1594();
    script2950(int1, int6, string2, int8, string3);
    LOGIN_RESETREPLY();
    return;
}