//
function script3704(int0: number, int1: number, int2: number, int3: number, int4: number, int5: number, int6: number, int7: number, int8: number): void {
    stack(13802);
    stack(int0);
    IF_SETGRAPHIC();
    stack(13803);
    stack(int1);
    IF_SETGRAPHIC();
    stack(13804);
    stack(int2);
    IF_SETGRAPHIC();
    stack(13817);
    stack(int3);
    IF_SETGRAPHIC();
    stack(13818);
    stack(int4);
    IF_SETGRAPHIC();
    stack(13819);
    stack(int5);
    IF_SETGRAPHIC();
    stack(13832);
    stack(int6);
    IF_SETGRAPHIC();
    stack(13833);
    stack(int7);
    IF_SETGRAPHIC();
    stack(13834);
    stack(int8);
    IF_SETGRAPHIC();
    return;
}