//[proc,aif_textinputbox]
function script4537(int0: component): void {
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETSIZE(40, 52, 1, 1);
    CC_SETPOSITION(0, 0, 1, 1);
    CC_SETGRAPHIC(6098 as graphic);
    CC_SETTILING(true);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETSIZE(40, 26, 1, 0);
    CC_SETPOSITION(0, 0, 1, 0);
    CC_SETGRAPHIC(6096 as graphic);
    CC_SETTILING(true);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETSIZE(40, 26, 1, 0);
    CC_SETPOSITION(0, 0, 1, 2);
    CC_SETGRAPHIC(6096 as graphic);
    CC_SETTILING(true);
    CC_SETVFLIP(true);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETSIZE(10, 52, 0, 1);
    CC_SETPOSITION(0, 0, 0, 1);
    CC_SETGRAPHIC(6097 as graphic);
    CC_SETTILING(true);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETSIZE(10, 52, 0, 1);
    CC_SETPOSITION(0, 0, 2, 1);
    CC_SETGRAPHIC(6097 as graphic);
    CC_SETTILING(true);
    CC_SETHFLIP(true);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETSIZE(20, 26, 0, 0);
    CC_SETPOSITION(0, 0, 0, 0);
    CC_SETGRAPHIC(6095 as graphic);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETSIZE(20, 26, 0, 0);
    CC_SETPOSITION(0, 0, 2, 0);
    CC_SETGRAPHIC(6095 as graphic);
    CC_SETHFLIP(true);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETSIZE(20, 26, 0, 0);
    CC_SETPOSITION(0, 0, 0, 2);
    CC_SETGRAPHIC(6095 as graphic);
    CC_SETVFLIP(true);
    CC_CREATE(int0, 5, IF_GETNEXTSUBID(int0));
    CC_SETSIZE(20, 26, 0, 0);
    CC_SETPOSITION(0, 0, 2, 2);
    CC_SETGRAPHIC(6095 as graphic);
    CC_SETVFLIP(true);
    CC_SETHFLIP(true);
    return;
}