//
function script3705(int0: number, int1: number, int2: number, int3: number, int4: number, int5: number, int6: number, int7: number, int8: number): void {
    stack(13805);
    stack(int0);
    IF_SETGRAPHIC();
    stack(13806);
    stack(int1);
    IF_SETGRAPHIC();
    stack(13807);
    stack(int2);
    IF_SETGRAPHIC();
    stack(13820);
    stack(int3);
    IF_SETGRAPHIC();
    stack(13821);
    stack(int4);
    IF_SETGRAPHIC();
    stack(13822);
    stack(int5);
    IF_SETGRAPHIC();
    stack(13835);
    stack(int6);
    IF_SETGRAPHIC();
    stack(13836);
    stack(int7);
    IF_SETGRAPHIC();
    stack(13837);
    stack(int8);
    IF_SETGRAPHIC();
    return;
}