//
function script3704(int0: unknown_int, int1: unknown_int, int2: unknown_int, int3: unknown_int, int4: unknown_int, int5: unknown_int, int6: unknown_int, int7: unknown_int, int8: unknown_int): void {
    stack(13802);
    stack(int0);
    IF_SETGRAPHIC();
    stack(13803);
    stack(int1);
    IF_SETGRAPHIC();
    stack(13804);
    stack(int2);
    IF_SETGRAPHIC();
    stack(13817);
    stack(int3);
    IF_SETGRAPHIC();
    stack(13818);
    stack(int4);
    IF_SETGRAPHIC();
    stack(13819);
    stack(int5);
    IF_SETGRAPHIC();
    stack(13832);
    stack(int6);
    IF_SETGRAPHIC();
    stack(13833);
    stack(int7);
    IF_SETGRAPHIC();
    stack(13834);
    stack(int8);
    IF_SETGRAPHIC();
    return;
}