//
function script3706(int0: number, int1: number, int2: number, int3: number, int4: number, int5: number, int6: number, int7: number, int8: number): void {
    stack(13799);
    stack(int0);
    IF_SETGRAPHIC();
    stack(13800);
    stack(int1);
    IF_SETGRAPHIC();
    stack(13801);
    stack(int2);
    IF_SETGRAPHIC();
    stack(13814);
    stack(int3);
    IF_SETGRAPHIC();
    stack(13815);
    stack(int4);
    IF_SETGRAPHIC();
    stack(13816);
    stack(int5);
    IF_SETGRAPHIC();
    stack(13829);
    stack(int6);
    IF_SETGRAPHIC();
    stack(13830);
    stack(int7);
    IF_SETGRAPHIC();
    stack(13831);
    stack(int8);
    IF_SETGRAPHIC();
    return;
}