//
function script13505(int0: obj, int1: unknown_int, int2: int): void {
    var int3 = INV_GETVAR(93 as inv, int2, 1091);
    if (((int2 == -1) || (int3 == 0))) {
        stack(OC_IOP(int0, 1));
        OC_ICURSOR(int0, 1);
        stack("");
        stack(-1);
        stack("");
        stack(-1);
        stack("");
        stack(-1);
        stack(OC_IOP(int0, 5));
        OC_ICURSOR(int0, 5);
        stack(int0);
        stack(5410);
        item_getparam();
        stack(int0);
        stack(5411);
        item_getparam();
        stack(int0);
        stack(5412);
        item_getparam();
        script2410(stack(), OC_NAME(int0), int1);
        return;
    };
    var int4 = -1;
    var int5 = -1;
    [int4, int5] = script13504(int3);
    stack(OC_IOP(int0, 1));
    OC_ICURSOR(int0, 1);
    stack(17);
    stack(36);
    stack(680);
    stack(int4);
    enum_getvalue();
    OC_ICURSOR(int0, 2);
    stack(17);
    stack(36);
    stack(680);
    stack(int5);
    enum_getvalue();
    OC_ICURSOR(int0, 3);
    stack("");
    stack(-1);
    stack(OC_IOP(int0, 5));
    OC_ICURSOR(int0, 5);
    stack(int0);
    stack(5410);
    item_getparam();
    stack(int0);
    stack(5411);
    item_getparam();
    stack(int0);
    stack(5412);
    item_getparam();
    script2410(stack(), OC_NAME(int0), int1);
    CC_SETONVARTRANSMIT(callback());
    return;
}