//
function script4706(int0: component): void {
    if ((int0 == comp(-1, 65535))) {
        return;
    };
    CC_DELETEALL(int0);
    var int1 = 0;
    int1 = IF_GETNEXTSUBID(int0);
    CC_CREATE(int0, 3, int1);
    CC_SETPOSITION(0, 0, 1, 1);
    CC_SETSIZE(0, 0, 1, 1);
    CC_SETFILL(1);
    CC_SETCOLOUR(921102);
    CC_SETTRANS(128);
    int1 = IF_GETNEXTSUBID(int0);
    CC_CREATE(int0, 5, int1);
    CC_SETPOSITION(0, 0, 0, 0);
    CC_SETSIZE(10, 10, 0, 0);
    CC_SETGRAPHIC(5475 as graphic);
    CC_SETHFLIP(true);
    CC_SETTILING(true);
    CC_SETTRANS(128);
    int1 = IF_GETNEXTSUBID(int0);
    CC_CREATE(int0, 5, int1);
    CC_SETPOSITION(0, 0, 2, 0);
    CC_SETSIZE(10, 10, 0, 0);
    CC_SETGRAPHIC(5475 as graphic);
    CC_SETTILING(true);
    CC_SETTRANS(128);
    int1 = IF_GETNEXTSUBID(int0);
    CC_CREATE(int0, 5, int1);
    CC_SETPOSITION(0, 0, 0, 2);
    CC_SETSIZE(10, 10, 0, 0);
    CC_SETGRAPHIC(5475 as graphic);
    CC_SETHFLIP(true);
    CC_SETVFLIP(true);
    CC_SETTILING(true);
    CC_SETTRANS(128);
    int1 = IF_GETNEXTSUBID(int0);
    CC_CREATE(int0, 5, int1);
    CC_SETPOSITION(0, 0, 2, 2);
    CC_SETSIZE(10, 10, 0, 0);
    CC_SETGRAPHIC(5475 as graphic);
    CC_SETVFLIP(true);
    CC_SETTILING(true);
    CC_SETTRANS(128);
    int1 = IF_GETNEXTSUBID(int0);
    CC_CREATE(int0, 5, int1);
    CC_SETPOSITION(0, 0, 1, 2);
    CC_SETSIZE(20, 10, 1, 0);
    CC_SETGRAPHIC(5474 as graphic);
    CC_SETVFLIP(true);
    CC_SETHFLIP(true);
    CC_SETTRANS(128);
    int1 = IF_GETNEXTSUBID(int0);
    CC_CREATE(int0, 5, int1);
    CC_SETPOSITION(0, 0, 1, 0);
    CC_SETSIZE(20, 10, 1, 0);
    CC_SETGRAPHIC(5474 as graphic);
    CC_SETTILING(true);
    CC_SETTRANS(128);
    int1 = IF_GETNEXTSUBID(int0);
    CC_CREATE(int0, 5, int1);
    CC_SETPOSITION(0, 0, 2, 1);
    CC_SETSIZE(10, 20, 0, 1);
    CC_SETGRAPHIC(5476 as graphic);
    CC_SETTILING(true);
    CC_SETTRANS(128);
    int1 = IF_GETNEXTSUBID(int0);
    CC_CREATE(int0, 5, int1);
    CC_SETPOSITION(0, 0, 0, 1);
    CC_SETSIZE(10, 20, 0, 1);
    CC_SETGRAPHIC(5476 as graphic);
    CC_SETTILING(true);
    CC_SETHFLIP(true);
    CC_SETTRANS(128);
    return;
}